<application>
  <component name="AppStorage">
    <histories>
      <item value="reviewer Opinion" />
      <item value="复核人意见" />
      <item value="advice From The Legal Clerk" />
      <item value="法务员意见" />
      <item value="问题代码" />
      <item value="single Back" />
      <item value="退单" />
      <item value="chargeback" />
      <item value="receive Time" />
      <item value="audit Time" />
      <item value="审核" />
      <item value="接收" />
      <item value="Sample" />
      <item value="amount" />
      <item value="金额" />
      <item value="money" />
      <item value="name Of Counterparty" />
      <item value="name Of Our Unit" />
      <item value="unit Dept" />
      <item value="create Dept" />
      <item value="create Person" />
      <item value="origin" />
      <item value="orgin" />
      <item value="pathspec 'project'' did not match any file(s) known to git. " />
      <item value=" Paths with -a does not make sense." />
      <item value="card Screen Content" />
      <item value="card All" />
      <item value="creator" />
      <item value="get Org Name Lang Json Array 4 Notify" />
      <item value="晚上见" />
      <item value="Your online security is important to us. Please wait while we secure your connection ..." />
      <item value="alter" />
      <item value="alert" />
      <item value="addition Sign" />
      <item value="eval" />
      <item value="control Address Attr Default Value Self" />
      <item value="豆蔻年华" />
      <item value="Data Integrity Violation Exception" />
      <item value="Unable to infer base url. This is common when using dynamic servlet registration or when the API is behind an API Gateway. The base url is the root of where all the swagger resources are served. For e.g. if the api is available at http://example.org/api/v2/api-docs then the base url is http://example.org/api/. Please enter the location manually: " />
      <item value="Socket Dispatcher" />
      <item value="Exception occured. Channel: [id: 0xaecd4391, L:/127.0.0.1:51828 - R:localhost/127.0.0.1:6379]&#10;java.io.IOException: 远程主机强迫关闭了一个现有的连接。" />
      <item value="Exception occured" />
      <item value="occured" />
      <item value="17:48:16.456 [redisson-netty-1-8] ERROR o.r.c.h.CommandsQueue - [exceptionCaught,153] - Exception occured. Channel: [id: 0x636b36de, L:/127.0.0.1:50883 - R:localhost/127.0.0.1:6379]" />
      <item value="root of context hierarchy" />
      <item value="The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server." />
      <item value="Failed to execute CommandLineRunner" />
      <item value="Auto Configuration Report Logging Initializer" />
      <item value="Connection refused: connect" />
      <item value="Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure" />
    </histories>
    <option name="languageScores">
      <map>
        <entry key="CHINESE" value="4497" />
        <entry key="ENGLISH" value="4585" />
        <entry key="FRENCH" value="47" />
        <entry key="PORTUGUESE" value="31" />
        <entry key="SPANISH" value="10" />
      </map>
    </option>
  </component>
  <component name="Settings">
    <option name="foldOriginal" value="true" />
    <option name="ignoreRegExp" value="" />
    <option name="translator" value="ai.youdao" />
    <option name="youdaoTranslateSettings">
      <youdao-translate>
        <option name="appId" value="790d8c17d9b6123c" />
        <option name="appKeyConfigured" value="true" />
      </youdao-translate>
    </option>
  </component>
</application>